.PHONY: clean All

All:
	@echo "----------Building project:[ ura_ecs_system - Debug ]----------"
	@cd "MISCONCEPT_SYSTEM_ALPHA_001" && "$(MAKE)" -f  "ura_ecs_system.mk"
clean:
	@echo "----------Cleaning project:[ ura_ecs_system - Debug ]----------"
	@cd "MISCONCEPT_SYSTEM_ALPHA_001" && "$(MAKE)" -f  "ura_ecs_system.mk" clean
